package me.nbarudi.files.roles;

public enum RoleAbilities {
	
	KILL, ROLEBLOCK, JAIL, JAILKILL, DOUSEIGNITE, INVEST, GETROLE, RAMPAGE, ALERT, GUARD, HEAL, NONE, REVEAL, WATCH, SUSCHECK, VAMPCHECK, BUG, FRAME, REZ, SWAP, CONTROL, REMEMBER, VEST, PUNISH,
	BM, DISGUISE, FORGE, CLEAN;

}
